services:
  - type: web
    name: turtle-stock-api
    env: python
    plan: free
    buildCommand: pip install -r backend/requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PORT
        value: 8000
      - key: DATABASE_URL
        sync: false
      - key: FINNHUB_API_KEY
        sync: false
      - key: JWT_SECRET_KEY
        sync: false
      - key: ALGORITHM
        value: HS256
      - key: ACCESS_TOKEN_EXPIRE_MINUTES
        value: 30
      - key: NODE_ENV
        value: production
      - key: DAILY_TASKS_TOKEN
        sync: false
    healthCheckPath: /health
    autoDeploy: true 