"""add_portfolio_enhancements

Revision ID: 26d1c0935417
Revises: c53528d587ff
Create Date: 2025-07-05 16:37:17.522904

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '26d1c0935417'
down_revision: Union[str, Sequence[str], None] = 'c53528d587ff'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_market_analysis_status_id'), table_name='market_analysis_status')
    op.drop_table('market_analysis_status')
    op.add_column('portfolios', sa.Column('stop_loss_price', sa.Float(), nullable=True))
    # ### end Alembic commands ###
    
    # ### manually added commands ###
    op.create_table('trade_history',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('symbol', sa.VARCHAR(), nullable=False),
    sa.Column('initial_value', sa.FLOAT(), nullable=False),
    sa.Column('end_value', sa.FLOAT(), nullable=False),
    sa.Column('net_value', sa.FLOAT(), nullable=False),
    sa.Column('shares', sa.FLOAT(), nullable=False),
    sa.Column('buy_price', sa.FLOAT(), nullable=False),
    sa.Column('sell_price', sa.FLOAT(), nullable=False),
    sa.Column('buy_date', sa.DATETIME(timezone=True), nullable=False),
    sa.Column('sell_date', sa.DATETIME(timezone=True), nullable=False),
    sa.Column('created_at', sa.DATETIME(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_trade_history_id'), 'trade_history', ['id'], unique=False)
    # ### end manually added commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('portfolios', 'stop_loss_price')
    op.create_table('market_analysis_status',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('last_run', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_market_analysis_status_id'), 'market_analysis_status', ['id'], unique=False)
    # ### end Alembic commands ###
    
    # ### manually added commands ###
    op.drop_index(op.f('ix_trade_history_id'), table_name='trade_history')
    op.drop_table('trade_history')
    # ### end manually added commands ###
