"""add is_added_up to portfolios

Revision ID: 47fdfd0088ae
Revises: 620794719df0
Create Date: 2025-07-07 16:20:10.450293

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '47fdfd0088ae'
down_revision: Union[str, Sequence[str], None] = '620794719df0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_market_analysis_status_id'), table_name='market_analysis_status')
    op.drop_table('market_analysis_status')
    op.add_column('portfolios', sa.Column('is_added_up', sa.Integer(), nullable=True))
    op.drop_column('portfolios', 'add_up_points')
    op.drop_column('portfolios', 'add_up_status')
    op.drop_column('portfolios', 'trailing_stop')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('portfolios', sa.Column('trailing_stop', sa.FLOAT(), nullable=True))
    op.add_column('portfolios', sa.Column('add_up_status', sa.INTEGER(), nullable=True))
    op.add_column('portfolios', sa.Column('add_up_points', sa.TEXT(), nullable=True))
    op.drop_column('portfolios', 'is_added_up')
    op.create_table('market_analysis_status',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('last_run', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_market_analysis_status_id'), 'market_analysis_status', ['id'], unique=False)
    # ### end Alembic commands ###
