"""Add add-up fields to Portfolio model

Revision ID: 620794719df0
Revises: 26d1c0935417
Create Date: 2025-07-07 11:43:27.094724

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '620794719df0'
down_revision: Union[str, Sequence[str], None] = '26d1c0935417'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_market_analysis_status_id'), table_name='market_analysis_status')
    op.drop_table('market_analysis_status')
    op.add_column('portfolios', sa.Column('add_up_status', sa.Integer(), nullable=True))
    op.add_column('portfolios', sa.Column('add_up_points', sa.Text(), nullable=True))
    op.add_column('portfolios', sa.Column('trailing_stop', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('portfolios', 'trailing_stop')
    op.drop_column('portfolios', 'add_up_points')
    op.drop_column('portfolios', 'add_up_status')
    op.create_table('market_analysis_status',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('last_run', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_market_analysis_status_id'), 'market_analysis_status', ['id'], unique=False)
    # ### end Alembic commands ###
