"""add signal model and user risk/capital

Revision ID: 7a008d9c7a60
Revises: 
Create Date: 2025-07-05 11:36:39.765324

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7a008d9c7a60'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('signals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('symbol', sa.String(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('close', sa.Float(), nullable=True),
    sa.Column('high_20d', sa.Float(), nullable=True),
    sa.Column('sma_50d', sa.Float(), nullable=True),
    sa.Column('sma_200d', sa.Float(), nullable=True),
    sa.Column('high_52w', sa.Float(), nullable=True),
    sa.Column('atr', sa.Float(), nullable=True),
    sa.Column('stop_loss', sa.Float(), nullable=True),
    sa.Column('position_size', sa.Integer(), nullable=True),
    sa.Column('signal_triggered', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_signals_date'), 'signals', ['date'], unique=False)
    op.create_index(op.f('ix_signals_id'), 'signals', ['id'], unique=False)
    op.create_index(op.f('ix_signals_symbol'), 'signals', ['symbol'], unique=False)
    op.drop_index(op.f('ix_good_stocks_id'), table_name='good_stocks')
    op.drop_index(op.f('ix_good_stocks_ticker'), table_name='good_stocks')
    op.drop_table('good_stocks')
    op.drop_index(op.f('ix_notifications_id'), table_name='notifications')
    op.drop_table('notifications')
    op.add_column('users', sa.Column('risk_tolerance', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('capital', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'capital')
    op.drop_column('users', 'risk_tolerance')
    op.create_table('notifications',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=True),
    sa.Column('ticker', sa.VARCHAR(), nullable=True),
    sa.Column('message', sa.VARCHAR(), nullable=True),
    sa.Column('is_read', sa.BOOLEAN(), nullable=True),
    sa.Column('timestamp', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notifications_id'), 'notifications', ['id'], unique=False)
    op.create_table('good_stocks',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('ticker', sa.VARCHAR(), nullable=True),
    sa.Column('price', sa.FLOAT(), nullable=True),
    sa.Column('score', sa.FLOAT(), nullable=True),
    sa.Column('timestamp', sa.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_good_stocks_ticker'), 'good_stocks', ['ticker'], unique=False)
    op.create_index(op.f('ix_good_stocks_id'), 'good_stocks', ['id'], unique=False)
    op.drop_index(op.f('ix_signals_symbol'), table_name='signals')
    op.drop_index(op.f('ix_signals_id'), table_name='signals')
    op.drop_index(op.f('ix_signals_date'), table_name='signals')
    op.drop_table('signals')
    # ### end Alembic commands ###
