"""add market analysis status table

Revision ID: c53528d587ff
Revises: 0c96ce786989
Create Date: 2025-07-05 13:42:39.104166

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c53528d587ff'
down_revision: Union[str, Sequence[str], None] = '0c96ce786989'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_market_analysis_status_id', table_name='market_analysis_status')
    op.drop_table('market_analysis_status')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('market_analysis_status',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('last_run', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_market_analysis_status_id', 'market_analysis_status', ['id'], unique=False)
    # ### end Alembic commands ###
